//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inmeta.Exception.Tests.ExceptionQueueReader {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionEntity", Namespace="http://schemas.datacontract.org/2004/07/Osiris.Exception.Service.Common")]
    [System.SerializableAttribute()]
    public partial class ExceptionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReporterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeSet {
            get {
                return this.ChangeSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeSetField, value) != true)) {
                    this.ChangeSetField = value;
                    this.RaisePropertyChanged("ChangeSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionTitle {
            get {
                return this.ExceptionTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTitleField, value) != true)) {
                    this.ExceptionTitleField = value;
                    this.RaisePropertyChanged("ExceptionTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reporter {
            get {
                return this.ReporterField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporterField, value) != true)) {
                    this.ReporterField = value;
                    this.RaisePropertyChanged("Reporter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheClass {
            get {
                return this.TheClassField;
            }
            set {
                if ((object.ReferenceEquals(this.TheClassField, value) != true)) {
                    this.TheClassField = value;
                    this.RaisePropertyChanged("TheClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheMethod {
            get {
                return this.TheMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.TheMethodField, value) != true)) {
                    this.TheMethodField = value;
                    this.RaisePropertyChanged("TheMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheSource {
            get {
                return this.TheSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.TheSourceField, value) != true)) {
                    this.TheSourceField = value;
                    this.RaisePropertyChanged("TheSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExceptionQueueReader.IExceptionQueueReader")]
    public interface IExceptionQueueReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exceptions.maritimesim.com/IExceptionQueueReader/GetException", ReplyAction="http://exceptions.maritimesim.com/IExceptionQueueReader/GetExceptionResponse")]
        Inmeta.Exception.Tests.ExceptionQueueReader.ExceptionEntity GetException();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExceptionQueueReaderChannel : Inmeta.Exception.Tests.ExceptionQueueReader.IExceptionQueueReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExceptionQueueReaderClient : System.ServiceModel.ClientBase<Inmeta.Exception.Tests.ExceptionQueueReader.IExceptionQueueReader>, Inmeta.Exception.Tests.ExceptionQueueReader.IExceptionQueueReader {
        
        public ExceptionQueueReaderClient() {
        }
        
        public ExceptionQueueReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExceptionQueueReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionQueueReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionQueueReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Inmeta.Exception.Tests.ExceptionQueueReader.ExceptionEntity GetException() {
            return base.Channel.GetException();
        }
    }
}
