//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Inmeta.Exception.Reporter.TFSExeptionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNewExceptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewApplicationExceptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExceptionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = "http://localhost:2119/service.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddNewExceptionCompletedEventHandler AddNewExceptionCompleted;
        
        /// <remarks/>
        public event AddNewApplicationExceptionCompletedEventHandler AddNewApplicationExceptionCompleted;
        
        /// <remarks/>
        public event GetExceptionsCompletedEventHandler GetExceptionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewException", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddNewException(string teamProject, string reporter, string comment, string version, string exceptionMessage, string exceptionType, string exceptionTitle, string stackTrace, string theClass, string theMethod, string theSource, string changeSet, string username) {
            this.Invoke("AddNewException", new object[] {
                        teamProject,
                        reporter,
                        comment,
                        version,
                        exceptionMessage,
                        exceptionType,
                        exceptionTitle,
                        stackTrace,
                        theClass,
                        theMethod,
                        theSource,
                        changeSet,
                        username});
        }
        
        /// <remarks/>
        public void AddNewExceptionAsync(string teamProject, string reporter, string comment, string version, string exceptionMessage, string exceptionType, string exceptionTitle, string stackTrace, string theClass, string theMethod, string theSource, string changeSet, string username) {
            this.AddNewExceptionAsync(teamProject, reporter, comment, version, exceptionMessage, exceptionType, exceptionTitle, stackTrace, theClass, theMethod, theSource, changeSet, username, null);
        }
        
        /// <remarks/>
        public void AddNewExceptionAsync(string teamProject, string reporter, string comment, string version, string exceptionMessage, string exceptionType, string exceptionTitle, string stackTrace, string theClass, string theMethod, string theSource, string changeSet, string username, object userState) {
            if ((this.AddNewExceptionOperationCompleted == null)) {
                this.AddNewExceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewExceptionOperationCompleted);
            }
            this.InvokeAsync("AddNewException", new object[] {
                        teamProject,
                        reporter,
                        comment,
                        version,
                        exceptionMessage,
                        exceptionType,
                        exceptionTitle,
                        stackTrace,
                        theClass,
                        theMethod,
                        theSource,
                        changeSet,
                        username}, this.AddNewExceptionOperationCompleted, userState);
        }
        
        private void OnAddNewExceptionOperationCompleted(object arg) {
            if ((this.AddNewExceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewExceptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewApplicationException", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddNewApplicationException(ExceptionEntity exceptionEntity) {
            this.Invoke("AddNewApplicationException", new object[] {
                        exceptionEntity});
        }
        
        /// <remarks/>
        public void AddNewApplicationExceptionAsync(ExceptionEntity exceptionEntity) {
            this.AddNewApplicationExceptionAsync(exceptionEntity, null);
        }
        
        /// <remarks/>
        public void AddNewApplicationExceptionAsync(ExceptionEntity exceptionEntity, object userState) {
            if ((this.AddNewApplicationExceptionOperationCompleted == null)) {
                this.AddNewApplicationExceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewApplicationExceptionOperationCompleted);
            }
            this.InvokeAsync("AddNewApplicationException", new object[] {
                        exceptionEntity}, this.AddNewApplicationExceptionOperationCompleted, userState);
        }
        
        private void OnAddNewApplicationExceptionOperationCompleted(object arg) {
            if ((this.AddNewApplicationExceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewApplicationExceptionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExceptions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExceptionEntity[] GetExceptions() {
            object[] results = this.Invoke("GetExceptions", new object[0]);
            return ((ExceptionEntity[])(results[0]));
        }
        
        /// <remarks/>
        public void GetExceptionsAsync() {
            this.GetExceptionsAsync(null);
        }
        
        /// <remarks/>
        public void GetExceptionsAsync(object userState) {
            if ((this.GetExceptionsOperationCompleted == null)) {
                this.GetExceptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExceptionsOperationCompleted);
            }
            this.InvokeAsync("GetExceptions", new object[0], this.GetExceptionsOperationCompleted, userState);
        }
        
        private void OnGetExceptionsOperationCompleted(object arg) {
            if ((this.GetExceptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExceptionsCompleted(this, new GetExceptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExceptionEntity {
        
        private string applicationNameField;
        
        private string reporterField;
        
        private string commentField;
        
        private string versionField;
        
        private string exceptionMessageField;
        
        private string exceptionTypeField;
        
        private string exceptionTitleField;
        
        private string stackTraceField;
        
        private string theClassField;
        
        private string theMethodField;
        
        private string theSourceField;
        
        private string changeSetField;
        
        private string usernameField;
        
        /// <remarks/>
        public string ApplicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        public string Reporter {
            get {
                return this.reporterField;
            }
            set {
                this.reporterField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionMessage {
            get {
                return this.exceptionMessageField;
            }
            set {
                this.exceptionMessageField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionType {
            get {
                return this.exceptionTypeField;
            }
            set {
                this.exceptionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionTitle {
            get {
                return this.exceptionTitleField;
            }
            set {
                this.exceptionTitleField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        public string TheClass {
            get {
                return this.theClassField;
            }
            set {
                this.theClassField = value;
            }
        }
        
        /// <remarks/>
        public string TheMethod {
            get {
                return this.theMethodField;
            }
            set {
                this.theMethodField = value;
            }
        }
        
        /// <remarks/>
        public string TheSource {
            get {
                return this.theSourceField;
            }
            set {
                this.theSourceField = value;
            }
        }
        
        /// <remarks/>
        public string ChangeSet {
            get {
                return this.changeSetField;
            }
            set {
                this.changeSetField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddNewExceptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AddNewApplicationExceptionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetExceptionsCompletedEventHandler(object sender, GetExceptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExceptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExceptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExceptionEntity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExceptionEntity[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591