//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueTool.ExceptionQueueReader {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExceptionQueueReader.IExceptionQueueReader")]
    public interface IExceptionQueueReader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExceptionQueueReader/GetException", ReplyAction="http://tempuri.org/IExceptionQueueReader/GetExceptionResponse")]
        Inmeta.Exception.Service.Common.ExceptionEntity GetException();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExceptionQueueReaderChannel : QueueTool.ExceptionQueueReader.IExceptionQueueReader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExceptionQueueReaderClient : System.ServiceModel.ClientBase<QueueTool.ExceptionQueueReader.IExceptionQueueReader>, QueueTool.ExceptionQueueReader.IExceptionQueueReader {
        
        public ExceptionQueueReaderClient() {
        }
        
        public ExceptionQueueReaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExceptionQueueReaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionQueueReaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExceptionQueueReaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Inmeta.Exception.Service.Common.ExceptionEntity GetException() {
            return base.Channel.GetException();
        }
    }
}
